version: '3.9'

services:

  postgresql:
    image: 'bitnami/postgresql:15.1.0'
    ports:
      - '5432:5432'
    volumes:
      - 'bank:/db'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=bank
    networks:
      - banking-app

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - banking-app

  kafka:
    image: docker.io/bitnami/kafka:3.2
    container_name: kafka
    ports:
       - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - banking-app

  kafka-magic:
    image: digitsy/kafka-magic:3.0.2.4
    container_name: kafka-magic
    ports:
      - "5000:80"
    networks:
      - banking-app
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"
      KMAGIC_ALLOW_SCHEMA_DELETE: "true"

volumes:
  bank:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  banking-app:
