version: '3.9'

services:

  # Database
  postgresql:
    image: 'bitnami/postgresql:15.1.0'
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'bank:/db'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=bank
    networks:
      - banking-app

  # Kafka
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - banking-app

  kafka:
    image: docker.io/bitnami/kafka:3.2
    container_name: kafka
    ports:
       - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - banking-app

  kafka-magic:
    image: digitsy/kafka-magic:3.0.2.4
    container_name: kafka-magic
    ports:
      - "5000:80"
    networks:
      - banking-app
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"
      KMAGIC_ALLOW_SCHEMA_DELETE: "true"

  # Banking app
  banking-system:
    image: remmo1/banking-app:0.0.1-SNAPSHOT
    container_name: banking-system
    ports:
      - "8080:8080"
    networks:
      - banking-app
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING.DATASOURCE.URL=jdbc:postgresql://postgres:5432/bank
    depends_on:
      - kafka

  cash-machine-dominikanski:
    image: remmo1/cashmachine:0.0.1-SNAPSHOT
    container_name: cash-machine-dominikanski
    ports:
      - "8001:8001"
    networks:
      - banking-app
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SERVER_PORT=8001
      - CASH.MACHINE.ID=CLl9wJzHaozsm2bKwzRppeCTjZHJhgFAZwLZpNYmdW8RVpIBfhxRtqACgxJHPaNh2TN2GFysp4IZXmkUd5RUXLFMyzA9B9hxjtut3wT7tuRssShfcKYNDW9WV0TNED8AeLERUETjow0jKcmnlyu31NsW1jyKvin6vebPv6omZw4oMQs3P2WbwIFUHVTc2tB5nosm9gHFpRFAwZaqfeHuWphedx8eh7HSdCRgPq4zwDjEewEnyDS6yFGBZwi8pxCutF2HddsPwgcpk16kQTOojKHmCcJPnEBfsYnx0b2muSlhIsDRW3OcZvBJztbID97BSgvGkCmbH8F602PZFM0X8YraCs6Cl9ef09UCIJ8QadAfb8VV007qooWBx1UF0RS6OaLndxhSW9JY9VxvOtVNwRFTvs0r2coh2CLTOoQ3r1Y0bbF5RvvlG2RcEvFLBZLX0YP48oi0qh7LjglFwgPzuLnH2jst2VM1yrg0QoMZmcQeVK88fg0r5YhUOmlBRBrzUuThXJI5pTHQMKi4jx9MsbnPzLX5WCnsl1umbsI2CQn1i82RB1BWrTrZOlZSdY8TnvxRioUrpuaNa8NV7vaa5m4IVyXG3nt48vZhMrR1qzYv7eJVzBxoxH8HlEwsWrKBj4nddjOmtUizYn6RzWxt3IjPln3cIym1C3h56iwfIBuFT1GSt1dZlpwFlN4KOXIVtlsZK71Me9SymATYiqvrcLKImO7QWA0ELnXkvQrWbbFw4ACvi5uEQ4DpjejbWG9IpcO9SFSGr6fDgEsvlIwSAf8pboqYmqYfnISaOs8F2QjJwa570kU6I7oGDyoHTyyp3OQyLfs0GDw8ziMOURsXtn30OCayoMMJZe8jdNLmadboWhLE9s7MGsRxftG8Rau5n6WrUOVYeRuxZdCQGUzo2xpQ58StcomNpTGWQw3RjgjSOYikkDPTHwFMzCmwh3y7g92BghyEMzjoduLEwsIWWdQg6TcQgqYZQPBaryvqpeIUDhRu0HKGTMHdPhTesFvP
    depends_on:
      - kafka

  cash-machine-grunwaldzki:
    image: remmo1/cashmachine:0.0.1-SNAPSHOT
    container_name: cash-machine-grunwaldzki
    ports:
      - "8002:8002"
    networks:
      - banking-app
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SERVER_PORT=8002
      - CASH.MACHINE.ID=z15wguPEIatrShhzXpAAlUnDZcGkw4yBP0nVuWyAjf28KIJBPQOKwkNfDjbCXs3xjWJbxzvhSqS5EOJ3GfelGIQzAxX05w6fpd2WvqV8IiAX8bIuuxjp1CFQGVFxyqj5hU3rK58JJzg0KHZzA0wjsNF0qrSqIYwKfyGYlbgzUZ4EiaJ402X4DPotewv290VvGLe1LBFQgqCtEUGxfm3ssOFxYB42VuZXeKGklVAh50egJTZg27gw40JIJ7WLcI1JohYaijL95QYmimHGJqtezHXQcWo6fG2MsbIEc0IBExMvZXAAw6IonaPTcmjSrX72mWBdo8k5A1Lry8epXuY9wUyRAvtL8YbKCYMghtoI2VRYN0ESVZ4I3CXmGHXoF0FTWYani4nUzsD15y6RiLaR3tjgIyDD1x7hvxdKt0bw1EKeUMqAJIpcVknrKunXFbA5r6Makmpa3ezfhjALPp72567wkqdI2MWXlsEiutqkb5exPiLLonzr66t09s9gQPPncemfRzQHmIxRVMeVb6YUyemtEhpZh5UgjvRzeRKeSGHkxj96cXa4pnbp7SVTN7aN80YwRM9gJxPUujEmGWsmtsfOKsRKP0b2cRTiaPiPMQDBXfFBBTWQ5AWDQX398XIybmWKI1D99nhAFTLjxWcdLezm3VSK2xtR9HoIcGqsyF4jYk7wrrXEIEVwyjlOXLYpniwSEXsE0dSuqyaufBfvqhi0XLPE01GdemPCJRvtd0KgONW7pL5ZrZAh0VS6LxwyMNnml5bWKzQtkrMu0gKGbUqpAhxtZSgYFKoBFxNYIDU9c3G5dXyGfzDMo2GvJyQYU9R7f4b2uY0EmSsSeeC0IM0Pbt09lvlXdgY9D1HNcXx7nWQ02U6UdEMNTLopokDq9PrWtbZ6yrnrM8aAFa8WHMcrV8cHNda104EXURVH97QnJ3YwNM2ohniSIbBweUQVhxcVf5N0pKQFeCYwIY5TG0Cxd1zqW4mBJJAfoXIwurh3NFLrAM1SLGB9UdIg4BW5
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  bank:

networks:
  banking-app:
