version: '3'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:15.1.0'
    ports:
      - '5432:5432'
    volumes:
      - 'bank:/db'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=bank

volumes:
  bank: